
@baseurl = localhost:8000


##################################################
# NORMAL USER LOGIN
##################################################

### Super User Login
# @name response
POST /auth/login HTTP/1.1
host: {{baseurl}}
content-type: application/x-www-form-urlencoded

username=normal@normal.com
&password=normal-pass

####
@access_token = {{response.response.body.access_token}}


####
GET /domains HTTP/1.1
host: {{baseurl}}
authorization: Bearer {{access_token}}

####
POST /domains HTTP/1.1
host: {{baseurl}}
authorization: Bearer {{access_token}}

{
  "url": "prefiromochilar"
}


####
POST /domains HTTP/1.1
host: {{baseurl}}
authorization: Bearer {{access_token}}

{
  "url": "prefiromochilar2"
}

####
GET /domains/1 HTTP/1.1
host: {{baseurl}}
authorization: Bearer {{access_token}}


####
DELETE /domains/2 HTTP/1.1
host: {{baseurl}}
authorization: Bearer {{access_token}}

