@baseurl = 54.162.97.209:8000
@baseurl = localhost:8000



##################################################
# FEAURES
##################################################

### Get all features
GET /ideas HTTP/1.1
host: {{baseurl}}


