
@baseurl = localhost:8000

####
POST /ranks HTTP/1.1
host: {{baseurl}}

{
  "rank": "89", 
  "keyword_id": 1
}


####
POST /ranks HTTP/1.1
host: {{baseurl}}

{
  "rank": "2", 
  "keyword_id": 1
}


####
POST /ranks HTTP/1.1
host: {{baseurl}}

{
  "rank": "12", 
  "keyword_id": 4
}

####
POST /ranks HTTP/1.1
host: {{baseurl}}

{
  "keyword": "Itália", 
  "domain_id": 2
}

####
GET /ranks HTTP/1.1
host: {{baseurl}}

####
GET /ranks/2 HTTP/1.1
host: {{baseurl}}

####
PUT /ranks/4 HTTP/1.1
host: {{baseurl}}

{
  "keyword": "blue", 
  "url_id": 1
}

####
DELETE /ranks/3 HTTP/1.1
host: {{baseurl}}


